# -*- coding: utf-8 -*-
"""Eva4_S11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cxO7IIMZHEfPB3rfEEIUjd04cvUmPFHe
"""
class LRrangeTest:
	def lr_range_test(self,model,train_loader,test_loader):
		class_names=["airplane","automobile","bird","cat","deer","dog","frog","horse","ship","truck"]
		from eva4statsmanager import StatsManager
		statsmanager=StatsManager()
		import torch.optim as optim
		from torch.optim.lr_scheduler import StepLR
		L2lambda=0
		L1lambda=0
		optimizer=optim.SGD(model.parameters(),lr=0.0001,momentum=0.9,nesterov=True,weight_decay=L2lambda)
		EPOCHS=30
		scheduler=StepLR(optimizer,step_size=1,gamma=1.4)
		model.gotrain(optimizer,train_loader,test_loader,EPOCHS,"/content/drive/My Drive",statsmanager,scheduler,False,L1lambda)
		statsmanager.plot_lr_accuracies()
		return statsmanager.give_max_lr()